Revert "replace gtest macro ASSERT_{NO_,}THROW with EXPECT to avoid clang-tidy warning cppcoreguidelines-avoid-goto"
This reverts commit abd0c9d23ddeef2f5695e90910c614e667ec2f66.

> tests/HdfFileTest.cpp:16:5: error: avoid using 'goto' for flow control [cppcoreguidelines-avoid-goto,-warnings-as-errors]
>     EXPECT_NO_THROW(file.get("Data"));
>     ^